/* #define MAX_ABS_MT_SLOT 9 */
#define MAX_ABS_MT_POSITION_X 1079
#define MAX_ABS_MT_POSITION_Y 2339
#define MAX_ABS_MT_TRACKING_ID 65535

#define KEY_TOGGLE_MOUSE KEY_LEFTCTRL

extern int MOUSE_BTN_LEFT_SLOT;
extern int MOUSE_MOVE_SLOT;
